### ISSUE TITLE
Show all IPs of a node

### ISSUE THREAD

**Issue by jsaguiar** [KI-labs/on-web-ui#12]
We should be able to show all ips associated with a node.

**Comment by jsaguiar** [comment]
specially IPMI. This can be fetched from Catalogs already but hard to get. It would be awesome to have it on a table

bonus: IPs might change (we are using dhcp). And when that happen catalogs are not updated. If we cannot solve this please create a new issue to fix it.

**Comment by danieltolmon** [comment]
Do you want me to show this information for the IP?

![Screenshot 2019-12-16 at 14 37 33](https://user-images.githubusercontent.com/44772295/70915383-a69c1080-2011-11ea-8831-6184c65484b3.png)

And this one from the IPMI?

![Screenshot 2019-12-16 at 14 31 26](https://user-images.githubusercontent.com/44772295/70915514-e06d1700-2011-11ea-986e-37a57b945d0a.png)


In the node table, for example in two columns (IP and IPMI) and behave like OBMs column that when you press appears a modal with the information

![Screenshot 2019-12-16 at 14 32 42](https://user-images.githubusercontent.com/44772295/70915010-0219ce80-2011-11ea-8a44-8786b78c22c2.png)

Or do just care about the IP address and I show just: 172.22.4.126 inside of the table

**Comment by jsaguiar** [comment]
we just care about IP

**Comment by danieltolmon** [comment]
Ok, So I add an extra column with the IP address. 
But I see a problem here, the catalog has a lot of information. And if we have to call each catalog for each node it will slow down a lot. Do you think it worth to do the same as de OBM's. The column shows a link, that if the user press I call the specific catalog and show the IP addresses through a modal. What do you think?
