### ISSUE TITLE
Page is not fully using window

### ISSUE THREAD

**Issue by jsaguiar** [KI-labs/on-web-ui#2]
Look at the menu on the left
![Screenshot 2019-11-28 at 10 40 06](https://user-images.githubusercontent.com/4295126/69799587-778d3e80-11cb-11ea-8079-8257eaca3111.png)

**Comment by danieltolmon** [comment]
I don't really understand what's the problem... Could you be more specific? :)

**Comment by jsaguiar** [comment]
<img width="1139" alt="Screenshot 2019-12-05 at 17 43 00" src="https://user-images.githubusercontent.com/4295126/70255216-b2bcde00-1786-11ea-8f8e-7e5d8f0ce5d1.png">

**Comment by danieltolmon** [comment]
Ahh ok, so you want that the page arrives till the bottom, isn't it? a html with hight 100vh
