### ISSUE TITLE
Selector broken 

### ISSUE THREAD

**Issue by jsaguiar** [KI-labs/on-web-ui#3]
In "Run workflow" view, selectors are broken (nodes....)

**Comment by danieltolmon** [comment]
I am sorry I don't understand the problem.
Which selectors do you mean?
![Screenshot 2019-12-11 at 14 50 43](https://user-images.githubusercontent.com/44772295/70631803-a7096580-1c25-11ea-9a8b-c2155bd80dc1.png)
