### ISSUE TITLE
Pre-select compute

### ISSUE THREAD

**Issue by jsaguiar** [KI-labs/on-web-ui#4]
The majority of times, we only want to see computes in Management Center. 
Please pre-select computes as default

**Comment by danieltolmon** [comment]
So, (to be clear), do you want the column type, in nodes table, to have the type sort ![Screenshot 2019-12-11 at 15 01 34](https://user-images.githubusercontent.com/44772295/70632653-25b2d280-1c27-11ea-8b89-c0f296ecc0e4.png)
 predefined as `computes`. And then if the user wants to see the enclosures or all of them, has to go to the type sort and delete compute? 

![Screenshot 2019-12-11 at 14 57 03](https://user-images.githubusercontent.com/44772295/70632336-8261bd80-1c26-11ea-9ee3-df566b7a0fdc.png)
