### ISSUE TITLE
Completely delete computes info

### ISSUE THREAD

**Issue by jsaguiar** [KI-labs/on-web-ui#5]
When we delete computes there is no need to keep there Obm and Enclosure nodes. It would be amazing to create a new action "delete and clean" (something like that), that would completely remove the node and everything related to it.

**Comment by danieltolmon** [comment]
I have added a button  where you can delete the node and related elements. I am already deleting the related Obms but I have some doubts about what else I have to delete.

This screenshot shows the node information. The related Obms is the first yellow marked. My question is... The second yellow marked is the enclosure node? (if it is, I have to also delete the Obms and related nodes from this node?) Do I have to delete something else? like skus or workflows?

![Screenshot 2019-12-16 at 11 17 15](https://user-images.githubusercontent.com/44772295/70903290-7dba5200-1ff6-11ea-9e85-bef40484daaa.png)
